### ISSUE TITLE
trackEvent method retrieves empty response

### ISSUE THREAD

**Issue by lrodriguezds** [talon-one/TalonOneJavaSdk#1]
I'm testing your sdk and I think there is a bug in _IntegrationApi_ class, at 
`public InlineResponse200 trackEvent(TrackEventBody body)` and `public ApiResponse<InlineResponse200> trackEventWithHttpInfo(TrackEventBody body)` exactly.

Right now I'm receiving empty responses.
Probably this happens because the return type is not right and the json deserialization doesn't work.

Shouldn't be `ApiResponse<InlineResponse20011>`?

**Comment by lrodriguezds** [comment]
Or should be `ApiResponse<Event>`

**Comment by zyxan** [comment]
Hi @lrodriguezds thanks for the report. This issue has been fixed [here](https://github.com/talon-one/TalonOneJavaSdk/commit/178d2256fcbeb739e00f9cefc3320d3fef6049c7).

We're migrating all those inline responses to named responses, and this was a residue of such unfinished migration.

This changes are not yet on our maven repository, only on `master` here, you can try them out cloning the repository or pulling the changes in your machine if you have it cloned already.

Thanks for the issue report 👍

**Comment by matorodriguez** [comment]
Hi Alex! Thanks for your work. Just a little detail: the javadoc still
says: "InlineResponse200".
Do you know when you'll release the maven artifact (say, version 1.2.1)?
Thanks again!

**Comment by zyxan** [comment]
@matorodriguez I just pushed the new version to the repository, it's available now 🎉💃
