### ISSUE TITLE
NumberFormatException calling ManagementApi.getRulesets()

### ISSUE THREAD

**Issue by lrodriguezds** [talon-one/TalonOneJavaSdk#2]
Hi guys!
We've found an issue calling `ManagementApi.getRulesets(applicationId, campaignId, null, null, null)` method. We're using your last java sdk (v 1.2.1)

The exception thrown is:
```
java.lang.NumberFormatException: For input string: "catch"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at one.talon.api.model.Rule.getEffects(Rule.java:151)
```

I think the problems is related with the response deserialization to an `InlineResponse2003` object. I paste the json response:
```
{
	"data": [{
		"id": 91,
		"created": "2018-08-28T12:54:22.303574Z",
		"campaignId": 45,
		"userId": 8,
		"rules": [{
			"title": "Rule básica",
			"condition": ["and", ["catch", false, ["do", [".", "Session", "Total"],
				[
					["Variable"],
					["\u003e", [".", "Variable"], 1]
				]
			]]],
			"effects": [
				["catch", ["noop"],
					["foreach", [".", "Session", "CartItems"],
						[
							["Item"],
							["setDiscountPerItem", "10% off per item", ["*", ["*", [".", "Item", "Quantity"],
										[".", "Item", "Price"]
									],
									["/", 10, 100]
								],
								[".", "Item", "Position"]
							]
						]
					]
				]
			]
		}],
		"rbVersion": "v2",
		"activatedAt": "2018-08-28T12:54:22.792927Z"
	}],
	"totalResultSize": 1
}
```

**Comment by zyxan** [comment]
@lrodriguezds thanks for reporting it! Already pushed a fix but would like to let it run and test it before releasing a new version 👯

**Comment by lrodriguezds** [comment]
Ok, thanks! I'll look forward for you fix. Regards!

**Comment by zyxan** [comment]
@lrodriguezds just released `1.2.2` with the fix. best!

**Comment by lrodriguezds** [comment]
Thanks for the ownership @zyxan.
Let me ask you one more question regarding this.

At https://developers.talon.one/management-api/reference/#getRulesets we see the `effect` attribute is simplest than the response retrieved by the Api. So, at our code we expect the response with the documented schema.
We don't know what means those `catch`, `noop` and `foreach` items, probably is something needed for talon.one's promotion engine.
Is the documentation old or the api is retrieving unnecessary information?

**Comment by TalonLaurens** [comment]
Hello @lrodriguezds , please send these types of questions to support@talon.one. We will gladly help you from there. :)

**Comment by fmoeckel** [comment]
Hello @lrodriguezds,

let me introduce myself: I'm Felix the customer integration engineer at Talon.one and happy to help you on all your current and upcoming questions regarding your integration process. 

Would you mind if we switch over to a mail conversation? I'll send you an introduction email in a minute.

Kindest regards, Felix
