### ISSUE TITLE
ApiClient constructor uses "==" operator to compare strings

### ISSUE THREAD

**Issue by tweckert-ecube** [talon-one/TalonOneJavaSdk#22]
Dear Talon.One team, 

the constructor of `ApiClient` uses the `==` operator to compare strings, for instance:
```
if (authenticationStrategy == "api_key_v1") {
   authentications.put("api_key_v1", new ApiKeyAuth("header", "Authorization"));
}
```
This will only work if these strings are "interned".

Instead, these strings should be compared using `equals`, for instance:
```
if ("api_key_v1".equals(authenticationStrategy)) {
   authentications.put("api_key_v1", new ApiKeyAuth("header", "Authorization"));
}
```

With kind regards, Thomas

**Comment by altJake** [comment]
Hi @tweckert-ecube ,

Thanks a lot for sending the issue!

This is a long time oversight and I am glad someone pointed that out, I am going to open a PR very soon to address it 👍

**Comment by tweckert-ecube** [comment]
Thank you very much!
