### ISSUE TITLE
CouponRejectionReason missing 

### ISSUE THREAD

**Issue by dahateb** [talon-one/TalonOneJavaSdk#5]
all of the Reasons specified here: http://developers.talon.one/Integration-API/Understanding-the-meta-response should be included  in the enum;
https://github.com/talon-one/TalonOneJavaSdk/blob/master/src/main/java/one/talon/model/CouponRejectionReason.java

**Comment by refs** [comment]
@dahateb thanks for reporting. This has been addressed in the [latest release](https://github.com/talon-one/TalonOneJavaSdk/blob/master/src/main/java/one/talon/model/CouponRejectionReason.java#L54)
